In [1]:
%config ZMQInteractiveShell.ast_node_interactivity='all'

import os
os.environ['JAVA_HOME'] = 'D:/Software/JDK_8U92'
PYTHON_PATH = 'D:/Software/anaconda3/envs/wk_py37/python'
os.environ['PYSPARK_DRIVER_PYTHON'] = PYTHON_PATH
os.environ['PYSPARK_PYTHON'] = PYTHON_PATH

from pyspark.sql import SparkSession, functions as F, Window
from pyspark.sql.types import StructType, StructField, LongType, StringType, FloatType


spark = SparkSession.builder.appName("TestEnv:Python Spark SQL basic example")\
            .master('local[*]')\
            .getOrCreate()

# 订单数据
order_rdd = spark.sparkContext.parallelize([
            (1, "2020-02-02"),
            (2, "2020-02-02"),
            (3, "2020-02-03"), 
            (4, "2020-02-04")])
order_schema = StructType([StructField("order_id", LongType(), True),
                     StructField("order_time", StringType(), True)])
orders_df = spark.createDataFrame(order_rdd, order_schema)


# 订单-产品数据
order_product_rdd = spark.sparkContext.parallelize([
            (1, 1, 1,  15.5, 5),
            (2, 1, 2,  22.0, 10),
            (3, 2, 2,  23.0, 15), 
            (4, 2, 3,  5.0, 20),
            (5, 2, 5,  6.9, 25)])
order_product_schema = StructType([StructField("id", LongType(), True),
                     StructField("order_id", StringType(), True),
                     StructField("product_id", LongType(), True),
                     StructField("price", FloatType(), True),
                     StructField("quantity", LongType(), True)])
order_product_df = spark.createDataFrame(order_product_rdd, order_product_schema)

orders_df.createOrReplaceTempView("orders")
order_product_df.createOrReplaceTempView("order_products")

orders_df.toPandas()
order_product_df.toPandas()

   id order_id  product_id  price  quantity
0   1        1           1   15.5         5
1   2        1           2   22.0        10
2   3        2           2   23.0        15
3   4        2           3    5.0        20
4   5        2           5    6.9        25